name: Manual EC2 Control

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose an action: start or stop"
        required: true
        default: "start"
        type: choice
        options:
          - start
          - stop

jobs:
  manage-ec2-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Current Time
        run: |
          echo "Current Time: $(date)"  # Debugging the current time

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Replace with your AWS region

      - name: Set EC2 Action
        id: set-action
        run: |
          # Get the action to be performed from the workflow dispatch input
          ACTION="${{ github.event.inputs.action }}"
          
          if [[ "$ACTION" == "start" ]]; then
            echo "action=start" >> $GITHUB_ENV
          elif [[ "$ACTION" == "stop" ]]; then
            echo "action=stop" >> $GITHUB_ENV
          else
            echo "action=none" >> $GITHUB_ENV
          fi

      - name: Manage EC2 Instance
        if: env.action != 'none'
        run: |
          INSTANCE_ID="i-1234567890abcdef0" # Replace with your EC2 instance ID

          if [[ "$action" == "start" ]]; then
            echo "Starting EC2 instance..."
            aws ec2 start-instances --instance-ids $INSTANCE_ID
          elif [[ "$action" == "stop" ]]; then
            echo "Stopping EC2 instance..."
            aws ec2 stop-instances --instance-ids $INSTANCE_ID
          fi
