name: Automatic EC2 Scheduler

on:
  schedule:
    # Start EC2 instance at 7:52 AM IST (Sunday to Friday)
    - cron: '22 2 * * 0-5'  # 2:22 AM UTC = 7:52 AM IST
    # Stop EC2 instance at 7:57 AM IST (Sunday to Friday)
    - cron: '27 2 * * 0-5'  # 2:27 AM UTC = 7:57 AM IST

jobs:
  manage-ec2-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Replace with your AWS region

      - name: Set EC2 Action
        id: set-action
        run: |
          # Get the current time of the cron job that triggered this workflow
          CRON_TIME="${{ github.event.schedule }}"
          
          if [[ "$CRON_TIME" == "22 2 * * 0-5" ]]; then
            echo "action=start" >> $GITHUB_ENV
          elif [[ "$CRON_TIME" == "27 2 * * 0-5" ]]; then
            echo "action=stop" >> $GITHUB_ENV
          else
            echo "action=none" >> $GITHUB_ENV
          fi

      - name: Manage EC2 Instance
        if: env.action != 'none'
        run: |
          INSTANCE_ID="i-1234567890abcdef0" # Replace with your EC2 instance ID

          if [[ "$action" == "start" ]]; then
            echo "Starting EC2 instance..."
            aws ec2 start-instances --instance-ids $INSTANCE_ID
          elif [[ "$action" == "stop" ]]; then
            echo "Stopping EC2 instance..."
            aws ec2 stop-instances --instance-ids $INSTANCE_ID
          fi
