name: Automatic EC2 Scheduler

on:
  schedule:
    # Stop EC2 instance at 12:00 Midnight IST (Sunday to Friday)
    - cron: '30 18 * * 0-5' # 18:30 UTC = 12:00 Midnight IST
    # Start EC2 instance at 08:00 AM IST (Sunday to Friday)
    - cron: '30 2 * * 0-5'  # 02:30 UTC = 08:00 AM IST

jobs:
  manage-ec2-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 # Replace with your AWS region

    - name: Determine EC2 Action
      id: determine-action
      run: |
        # Get the current schedule event (start or stop)
        if [[ "$GITHUB_EVENT_SCHEDULE" == "30 18 * * 0-5" ]]; then
          echo "action=stop" >> $GITHUB_ENV
        elif [[ "$GITHUB_EVENT_SCHEDULE" == "30 2 * * 0-5" ]]; then
          echo "action=start" >> $GITHUB_ENV
        else
          echo "action=none" >> $GITHUB_ENV
        fi

    - name: Manage EC2 Instance
      if: env.action != 'none'
      run: |
        INSTANCE_ID="i-03613c3a66bc4e6fd" # Replace with your EC2 instance ID
        INSTANCE_STATE=$(aws ec2 describe-instances \
          --instance-ids "$INSTANCE_ID" \
          --query "Reservations[*].Instances[*].State.Name" \
          --output text)

        if [[ "$action" == "start" && "$INSTANCE_STATE" != "running" ]]; then
          echo "Starting EC2 instance..."
          aws ec2 start-instances --instance-ids "$INSTANCE_ID"
        elif [[ "$action" == "stop" && "$INSTANCE_STATE" != "stopped" ]]; then
          echo "Stopping EC2 instance..."
          aws ec2 stop-instances --instance-ids "$INSTANCE_ID"
        else
          echo "No action needed. Instance is already in the desired state."
        fi
