name: EC2 Instance Automation

on:
  schedule:
    # Trigger at 7:10 AM IST (1:40 AM UTC) to stop the instance (Sunday to Friday)
    - cron: "40 1 * * 0-5"
    # Trigger at 7:13 AM IST (1:43 AM UTC) to start the instance (Sunday to Friday)
    - cron: "43 1 * * 0-5"

jobs:
  manage-ec2-instance:
    runs-on: ubuntu-latest

    env:
      INSTANCE_ID: i-03613c3a66bc4e6fd

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region=${{ secrets.AWS_REGION }}" >> ~/.aws/config

    - name: Stop EC2 Instance at 7:10 AM IST
      if: github.event.schedule == "40 1 * * 0-5"
      run: |
        aws ec2 stop-instances --instance-ids $INSTANCE_ID
        echo "EC2 instance $INSTANCE_ID stopped."

    - name: Start EC2 Instance at 7:13 AM IST
      if: github.event.schedule == "43 1 * * 0-5"
      run: |
        aws ec2 start-instances --instance-ids $INSTANCE_ID
        echo "EC2 instance $INSTANCE_ID started."
