name: Automatic EC2 Scheduler

on:
  schedule:
    # Stop EC2 instance at 12:00 AM IST (Sunday to Friday)
    - cron: '30 18 * * 0-5'  # 6:30 PM UTC = 12:00 AM IST
    # Start EC2 instance at 08:00 AM IST (Sunday to Friday)
    - cron: '30 2 * * 0-5'  # 2:30 AM UTC = 08:00 AM IST

jobs:
  manage-ec2-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Current Time
        run: |
          echo "Current Time: $(date)"  # Debugging the current time

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Replace with your AWS region

      - name: Set EC2 Action
        id: set-action
        run: |
          # Get the action to be performed from the workflow schedule
          CRON_TIME="${{ github.event.schedule }}"
          
          if [[ "$CRON_TIME" == "30 2 * * 0-5" ]]; then
            echo "action=start" >> $GITHUB_ENV
          elif [[ "$CRON_TIME" == "30 18 * * 0-5" ]]; then
            echo "action=stop" >> $GITHUB_ENV
          else
            echo "action=none" >> $GITHUB_ENV
          fi

      - name: Manage EC2 Instance
        if: env.action != 'none'
        run: |
          INSTANCE_ID="i-03613c3a66bc4e6fd" # Replace with your EC2 instance ID

          if [[ "$action" == "start" ]]; then
            echo "Starting EC2 instance..."
            aws ec2 start-instances --instance-ids $INSTANCE_ID
          elif [[ "$action" == "stop" ]]; then
            echo "Stopping EC2 instance..."
            aws ec2 stop-instances --instance-ids $INSTANCE_ID
          fi
