name: Simple Cron Test

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute for testing

jobs:
  test-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Display current time
        run: |
          echo "The cron job is working!"
          echo "Current UTC time: $(date -u)"
