name: Manual Test Workflow

on:
  workflow_dispatch:
    inputs:
      test_input:
        type: string
        description: 'Enter a test value'
        required: true

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Display Test Input
        run: |
          echo "Test input provided: ${{ github.event.inputs.test_input }}"
